name: Chestsell
version: "1.0"
author: Arnold
main: com.minecraftercity.chestsell.Main
api-version: 1.16
depend: [Vault, Factions]
commands:
  autosell:
    description: Point at a chest and items inside it will automatically be sold!
    usage: /autosell
    permission: autosell.use